# Generated by Django 4.2.7 on 2025-10-02 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_no', models.CharField(max_length=50, unique=True)),
                ('loan_no', models.CharField(max_length=50, unique=True)),
                ('pan', models.CharField(blank=True, max_length=20, null=True)),
                ('sanction_date', models.DateField()),
                ('disbursal_date', models.DateField()),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('tenure', models.IntegerField(blank=True, null=True)),
                ('repayment_date', models.DateField(blank=True, null=True)),
                ('repayment_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('processing_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('net_disbursal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('interest_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('collection_active', models.BooleanField(default=False)),
                ('fraud_status', models.CharField(max_length=20)),
                ('reloan_status', models.CharField(max_length=20)),
                ('total_received', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_received_date', models.DateField(blank=True, null=True)),
                ('outstanding', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('overdue_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('overdue_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('dpd_bucket', models.CharField(max_length=20)),
                ('closed_status', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loan Record',
                'verbose_name_plural': 'Loan Records',
                'ordering': ['-disbursal_date'],
                'indexes': [models.Index(fields=['repayment_date'], name='dashboard_l_repayme_051354_idx'), models.Index(fields=['dpd_bucket'], name='dashboard_l_dpd_buc_30ba62_idx'), models.Index(fields=['closed_status'], name='dashboard_l_closed__9f4811_idx'), models.Index(fields=['state'], name='dashboard_l_state_c8818e_idx'), models.Index(fields=['city'], name='dashboard_l_city_725f61_idx'), models.Index(fields=['repayment_date', 'dpd_bucket'], name='dashboard_l_repayme_33fb7c_idx'), models.Index(fields=['repayment_date', 'closed_status'], name='dashboard_l_repayme_f71622_idx'), models.Index(fields=['repayment_date', 'state'], name='dashboard_l_repayme_85e622_idx'), models.Index(fields=['repayment_date', 'city'], name='dashboard_l_repayme_d95eb8_idx')],
            },
        ),
    ]
